#! /usr/bin/env node

var http = require('http');
var http_proxy = require('http-proxy');
var url = require('url');

var routes = {
	"*": [
		"127.0.0.1:80",
		"127.0.0.2:80",
		"127.0.0.3:80"
	],
	"mango/jango" : [
		"127.0.0.1:333"
	],
	"mango/*" : [
		"127.0.0.1:444",
		"127.0.0.2:444"
	]
}

function pickRandom (list) {
	return list[Math.floor(Math.random()*list.length)];
}

function router (path) {
	var totalpath = '';
	var servers;
	
	for (var i=path.length; i>=0; i--) {
		totalpath = path.slice(0,i).join('/');
		servers = routes[totalpath];
		if (!servers) {
			servers = routes[totalpath + '/*'];
		}
		if (servers) {
			break;
		}
	}
	if (!servers) {
		servers = routes['*'];
	}
	return servers;
}

var proxy = http_proxy.createProxyServer({});

function requestHandler (req,res) {
	var path = url.parse(req.url).pathname.split('/').slice(1);
	
	var servers = router(path);
	
	if (servers) {
		var s = pickRandom(servers);
		console.log('Found server:', s);
		proxy.web(req,res,{ target: 'http://' + s });
	}
	else {
		console.log('No routes found');
		res.writeHead(404,{"Content-Type": "text/plain"});
		res.write('Not Found');
		res.end();
	}
	
	// process.exit();
}

http.createServer(requestHandler).listen(8888);
